local cfg = {
	LUA_MINSTACK = 20,
	LUA_MULTRET = -1,
	LUA_IDSIZE = 256,
	LUA_VECTOR_SIZE = 3,
	LUAI_MAXCALLS = 20000,
	BASIC_CI_SIZE = 8,
	EXTRA_STACK = 5,
	MAX_RECURSION = 19997
}

cfg.LUA_EXTRA_SIZE = cfg.LUA_VECTOR_SIZE - 2
cfg.BASIC_STACK_SIZE = cfg.LUA_MINSTACK * 2

return cfg